version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: webapp:express
    container_name: express1
    environment:
      MESSAGE: 'hello world'
    ports:
      - '3001:3001'
  webapp2:
    image: webapp:express
    container_name: express2
    depends_on:
      - webapp
    env_file: ./express.env
    ports:
      - '3002:3002'
  # webapp3:
  #   image: webapp:express
  #   depends_on:
  #     - webapp
  #   container_name: express3
  #   deploy:
  #     restart_policy:
  #       condition: on_failure
  #       max_attempts: 3
