version: '3.2'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.write
    image: webapp:express_write
    container_name: express_write
    environment:
      MESSAGE: 'hello world'
    ports:
      - '3001:3001'
    volumes:
      - 'data-volume:/express/logs'
      - ./node_modules:/express/node_modules
  webapp2:
    build:
      context: .
      dockerfile: Dockerfile.read
    image: webapp:express_read
    container_name: express_read
    depends_on:
      - webapp
    env_file: ./express.env
    ports:
      - '3002:3002'
    volumes:
      - 'data-volume:/express/logs'
      - ./node_modules:/express/node_modules
volumes:
  data-volume:
