version: '3'                        # different versions support different features
services:                           # service definition
  webapp:                           # name of service
    build:                          # build -def - I want the container to build if it doesn't exist
      context: .                    # same as standard docker build . 
      dockerfile: Dockerfile        # which docker file to use
    image: webapp:express           # the image to use, or image to create during the build step
    container_name: express1        # container name
    environment:                    # environement definition, using <key>: <value> here
      MESSAGE: 'hello world' 
    ports:                          # expose ports
      - '3001:3001'
  webapp2:                          # name of service
    image: webapp:express           # name of image
    container_name: express2        # name of container
    depends_on:                     # this service will start after the first service
      - webapp 
    env_file: ./express.env         # using an file to specify the environment this time
    ports: 
      - '3002:3002'                 # different ports
